add test condition
DOnEbrala/Epam_Test pull request #1
Opened 2023-01-08 12:13 UTC by DOnEbrala

test condition

2023-01-24 12:31 UTC, rimus requested changes

2023-01-24 12:31 UTC, rimus commented on page_objects/PageCondition.js
> +class condition extends Page {
Naming: **C**ondition.

2023-01-24 12:31 UTC, rimus commented on page_objects/check.js
> +module.exports = new Check
`new Check();`

2023-01-24 12:31 UTC, rimus commented on page_objects/PageCondition.js
> +    }
Need to add syntax highlighting steps.

2023-01-24 12:31 UTC, rimus commented on test/specs/test.spec.js
> +        await browser.pause(3000)
Please replace `browser.pause()`  with waiters (e.g. `waitForExist()`) → https://webdriver.io/docs/api/element/waitForExist

2023-01-24 12:31 UTC, rimus commented on test/specs/test.spec.js
> +});
Please check Bash on the page.

2023-01-24 15:07 UTC, DOnEbrala commented
Done

2023-02-09 12:12 UTC, rimus requested changes

2023-02-09 12:12 UTC, rimus commented on page_objects/PageCondition.js
> +    get PasteMainTextArea() {
Only classes should start with Capitals. Please rename methods and fields.

2023-02-09 12:12 UTC, rimus commented on page_objects/PageCondition.js
> +class Condition extends Page {
ConditionPage

2023-02-09 12:12 UTC, rimus commented on page_objects/check.js
>  class Check extends Page {
CheckPage

2023-02-09 12:12 UTC, rimus commented on page_objects/check.js
> +    get CheckBashIfExist(){
Only classes should start with Capitals. Please rename methods and fields.

2023-02-09 13:59 UTC, DOnEbrala commented
done

2023-02-09 14:07 UTC, merged